### ISSUE TITLE
RubySG Hackerdrinks Collab Meetup (May 2022), 2022-05-19

### ISSUE THREAD

**Issue by TayKangSheng** [rubysg/meetups#13]
## Description

![hackerdrinksxrubysg](https://user-images.githubusercontent.com/10722197/167282965-e0087927-0efa-4fe6-bed6-49f9a8e9ca1c.jpg)

🌵Yoz! 👋 It’s May 2022 and we are very happy to have a collab meetup with our friends from Hackerdrinks! This month, Adrian from Nodeflair will be sharing about how they use Searchkick gem (SK) to build certain search features with ElasticSearch (ES). After the talk, we will proceed to Timbre+ for meetup after party!

❗️❗️Please take note of the following important points:
1. For the health and safety of all our participants, all participants needs to be fully vaccinated to attend the meetup.
2. No Pizzas will be provided during the Meetup as we are still restricted by Covid measures.
3. No free beer is provided so BYOB during the after party.

➡️ Please RSVP here
https://www.meetup.com/Singapore-Ruby-Group/events/285800188
➡️ Find all details in the GitHub issue below.
https://github.com/rubysg/meetups/issues/13
➡️ Join the RubySG telegram group for more updates!
https://t.me/+j4v36nyUYNU4OWZl
➡️ Follow us on our website.
https://ruby.sg

## Plan

Date: 19th May
Location: Nodeflair

No food is provided because of limitations of covid measures for we will start the meetup at a later time. 

| Time | Event | 
| --- | --- |
| `7.00pm` | Meet and Greet at Nodeflair (Blk 71 Ayer Rajah Crescent 07-22, 139951. Nearest MRT is One-north) |
| `7.30pm` | Start of RubySG talk |
| `8.00pm` | Hackerdrinks at Timbre+ | 
| `9.30pm` | Official end of meetup, take photo and OTOT | 

Background
- This meetup, I will share about how we use [Searchkick gem](https://github.com/ankane/searchkick) (SK) to build certain search features with ElasticSearch (ES)
- What I will talk about
  - Why and how we use SK / ES (using it with ActiveRecord)
  - Using SK to index records into ES
  - How to query using SK using the different search options (pagination, limit etc.)
  - Reindexing options
  - Similarity search
  - Multi-search (batching search queries into 1 query)
  - (tentative) Highlights
  - (tentative) Stemming for better match
  - (tentative) Aggregations
- What I will NOT talk about
  - How to configure ES
  - Working with non-text data e.g. geospatial 

## Questions 

- [ ] How are we going to deal with the beer plan? 
    * beer in hackerspace? folks buy their own or sponsored? 
    * beer at a nearby place? 
- [ ] Find speaker for RubySG talk? Prepare comms early to see if anybody want to speak at this event? 
- [ ] Double confirm HackerspaceSG booking with Valentine

cc @davidchua

**Comment by davidchua** [comment]
Thanks for organizing this in an issue @TayKangSheng 

I think one of the concerns is finding a location in the area. Do you have a rough estimate on how many people might be interested to join the post-meetup drinks?

Some of the possible locations:
- Druggist
  - Although might be unlikely due to the size if we have > 10. Not sure if they would allow such a big size booking that might close up their entire indoor but if we have a confirmed/est. size, I could e-mail them
- The Refinery
  - Just opposite HSG, looks spacious, not sure if they will allow dynamic configuration (ie. people who just come and go)
- https://www.facebook.com/deckbar.sg/
  - At CT Hub, across the road on the other side, might need to walk for a bit, looks close to a bar/bistro type like Bluemist but never been there before, not sure about configuration
- https://www.facebook.com/auraloftbistro/
  - Also nearby, but never been before, photos looks configurable
- https://www.google.com/maps/place/Tocha+Bistro+%7C+Alfresco+Dining,+Bar+%26+Grill/@1.305791,103.8598655,3a,75y,320h,90t/data=!3m8!1e1!3m6!1sAF1QipN-2HJYTm27iFvjbR1ICrCobljspjoheBbH8Med!2e10!3e11!6shttps:%2F%2Flh5.googleusercontent.com%2Fp%2FAF1QipN-2HJYTm27iFvjbR1ICrCobljspjoheBbH8Med%3Dw203-h100-k-no-pi0-ya256.05994-ro-0-fo100!7i13312!8i6656!4m5!3m4!1s0x0:0x9af47d9334c964c4!8m2!3d1.3059212!4d103.8600094

**Comment by TayKangSheng** [comment]
The talk part of the meetup did not happen because we did not know if folks are going to turn up for the meetup. So we only proceeded with the drinks session!
